# Generated by Django 3.0.8 on 2020-07-29 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    # dependencies = [
    #     ('User', '0005_auto_20200723_1507'),
    # ]

    operations = [
        migrations.CreateModel(
            name='WikiNewsUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=200, null=True, unique=True)),
                ('password', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'WikiNewsUser',
            },
        ),
    ]
