# Generated by Django 3.0.7 on 2020-07-13 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('itemname', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('itemsummary', models.CharField(max_length=45)),
                ('lastupdated', models.DateField(max_length=45)),
            ],
            options={
                'db_table': 'Item',
            },
        ),
    ]
