# Generated by Django 3.0.7 on 2020-07-13 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WikiNews', '0002_itemdetails'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='itemdetails',
            table='ItemDetails',
        ),
    ]
