# Generated by Django 3.0.8 on 2020-07-20 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WikiNews', '0003_auto_20200713_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, null=True)),
                ('content', models.CharField(max_length=1000, null=True)),
            ],
            options={
                'db_table': 'Items',
            },
        ),
    ]
