# Generated by Django 3.0.8 on 2020-07-29 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WikiNews', '0004_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='WikiNewsItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500, null=True)),
                ('text', models.TextField()),
                ('image', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'WikiNewsItem',
            },
        ),
    ]
