# Generated by Django 3.0.8 on 2020-07-30 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WikiNews', '0005_wikinewsitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='wikinewsitem',
            name='lastUpdated',
            field=models.DateField(null=True),
        ),
    ]
