# Generated by Django 3.0.8 on 2020-07-30 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WikiNews', '0007_auto_20200729_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wikinewsitem',
            name='image',
            field=models.TextField(),
        ),
    ]
