# Generated by Django 2.2.14 on 2020-08-05 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WikiNews', '0008_auto_20200729_1925'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Items',
        ),
    ]
