# Generated by Django 2.2.14 on 2020-08-05 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WikiNews', '0009_delete_items'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItemDetails',
        ),
    ]
